---
swagger: "2.0"
info:
  description: "Blends content and style images in an artistic way, using Deep Neural\
    \ Networks"
  version: "1.0.0"
  title: "neural-style API"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /blend:
    post:
      tags:
      - "blend"
      summary: "Blends a content and a style image into a new image"
      description: "Blends a content and a style image into a new image. The style\
        \ image should preferrably be a picture with a marked artistic style, while\
        \ the content image can be a photo or other kind of picture. Weight of these\
        \ two input images in the resultant blend can be configured through parameters.\n"
      operationId: "controllers.blend_controller.blend_post"
      parameters:
      - name: "content"
        in: "formData"
        description: "Content image."
        required: true
        type: "file"
      - name: "style"
        in: "formData"
        description: "Style image."
        required: true
        type: "file"
      responses:
        200:
          description: "Blended image"
          schema:
            type: "string"
            format: "binary"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
